version: "3.9"
services:
    db:
        build: ./database/
        restart: always
        ports:
            - "5432:5432"
    app:
        build: ./app/
        links:
            - db
        depends_on: 
            - db
        volumes:
            - ./share:/build
        ports:
            - "5000:5000"
        command: sh -c "python app.py && cp data.json /build/"